'use client';

import { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import { Renderer } from '@openuidev/react-lang';
import { bestpathLibrary } from '@/lib/openui/library';
import { GeneratedCard } from './generated-card';

interface MessageContentProps {
  text: string;
  isStreaming?: boolean;
}

/* ─── Types ──────────────────────────────────────── */

interface RevealUnit {
  type: 'markdown' | 'openui';
  content: string;
}

/* ─── Splitting helpers ──────────────────────────── */

/**
 * Split plain markdown text into sealed paragraphs (followed by \n\n)
 * and an optional pending tail that is still being written.
 */
function splitMarkdownParagraphs(text: string): {
  sealed: string[];
  pending: string | null;
} {
  const boundaryRe = /\n\n+/g;
  const paragraphs: string[] = [];
  let lastEnd = 0;

  for (const match of text.matchAll(boundaryRe)) {
    const content = text.slice(lastEnd, match.index).trim();
    if (content) paragraphs.push(content);
    lastEnd = match.index + match[0].length;
  }

  const tail = text.slice(lastEnd).trim();
  if (tail) return { sealed: paragraphs, pending: tail };
  return { sealed: paragraphs, pending: null };
}

/**
 * Splits streaming text into reveal units.
 *
 * "Sealed" units are paragraphs/blocks that are complete — they are
 * followed by a paragraph break (\n\n) or a block boundary (```).
 *
 * "Pending" is the trailing unit still being generated by the model.
 * During streaming we hold it back; when streaming ends we show it.
 */
function splitRevealUnits(text: string): {
  sealed: RevealUnit[];
  pending: RevealUnit | null;
} {
  const sealed: RevealUnit[] = [];

  // Find all COMPLETE openui blocks (those with a closing ```)
  const completeBlockRe = /```openui\s*\n([\s\S]*?)```/g;
  const blocks: { start: number; end: number; content: string }[] = [];

  for (const match of text.matchAll(completeBlockRe)) {
    blocks.push({
      start: match.index,
      end: match.index + match[0].length,
      content: (match[1] ?? '').trim(),
    });
  }

  // Walk through the text, interleaving markdown paragraphs and openui blocks
  let cursor = 0;

  for (const block of blocks) {
    // Markdown before this block — all its paragraphs are sealed
    // because they're followed by a block boundary
    const mdBefore = text.slice(cursor, block.start);
    for (const p of mdBefore
      .split(/\n\n+/)
      .map((s) => s.trim())
      .filter(Boolean)) {
      sealed.push({ type: 'markdown', content: p });
    }

    // The openui block itself (complete — closing ``` was matched)
    if (block.content) {
      sealed.push({ type: 'openui', content: block.content });
    }

    cursor = block.end;
  }

  // Handle remaining text after the last complete block
  const remaining = text.slice(cursor);

  // Check for an INCOMPLETE openui block at the end (opening ``` but no closing)
  const incompleteIdx = remaining.indexOf('```openui');
  if (incompleteIdx !== -1) {
    // Markdown before the incomplete block
    const mdBefore = remaining.slice(0, incompleteIdx);
    for (const p of mdBefore
      .split(/\n\n+/)
      .map((s) => s.trim())
      .filter(Boolean)) {
      sealed.push({ type: 'markdown', content: p });
    }

    // The incomplete openui block is pending
    const body = remaining
      .slice(incompleteIdx)
      .replace(/^```openui\s*\n?/, '')
      .trim();
    return {
      sealed,
      pending: { type: 'openui', content: body },
    };
  }

  // Pure markdown remaining — split into paragraphs
  const { sealed: mdSealed, pending: mdPending } =
    splitMarkdownParagraphs(remaining);
  for (const p of mdSealed) {
    sealed.push({ type: 'markdown', content: p });
  }

  return {
    sealed,
    pending: mdPending ? { type: 'markdown', content: mdPending } : null,
  };
}

/* ─── Markdown component overrides ───────────────── */

const mdComponents: React.ComponentProps<typeof ReactMarkdown>['components'] =
  {
    h1: ({ children }) => (
      <h1 className="mt-5 mb-2 text-xl font-bold text-foreground">
        {children}
      </h1>
    ),
    h2: ({ children }) => (
      <h2 className="mt-4 mb-1.5 text-lg font-bold text-foreground">
        {children}
      </h2>
    ),
    h3: ({ children }) => (
      <h3 className="mt-3 mb-1 text-base font-semibold text-foreground">
        {children}
      </h3>
    ),
    h4: ({ children }) => (
      <h4 className="mt-3 mb-1 text-sm font-semibold text-text-muted">
        {children}
      </h4>
    ),
    p: ({ children }) => <p className="my-1">{children}</p>,
    strong: ({ children }) => (
      <strong className="font-semibold text-foreground">{children}</strong>
    ),
    ul: ({ children }) => (
      <ul className="my-1 ml-4 list-disc space-y-0.5">{children}</ul>
    ),
    ol: ({ children }) => (
      <ol className="my-1 ml-4 list-decimal space-y-0.5">{children}</ol>
    ),
    li: ({ children }) => <li>{children}</li>,
    a: ({ href, children }) => (
      <a
        href={href}
        className="text-primary underline decoration-primary/30 hover:decoration-primary"
      >
        {children}
      </a>
    ),
    code: ({ children, className }) => {
      const isBlock = className?.includes('language-');
      if (isBlock) {
        return (
          <pre className="my-1.5 overflow-x-auto rounded-lg bg-bg-inset p-3 text-xs">
            <code>{children}</code>
          </pre>
        );
      }
      return (
        <code className="rounded bg-bg-inset px-1 py-0.5 text-xs">
          {children}
        </code>
      );
    },
    pre: ({ children }) => <>{children}</>,
    hr: () => <hr className="my-2 border-border/50" />,
    blockquote: ({ children }) => (
      <blockquote className="my-1.5 border-l-2 border-primary/30 pl-3 italic text-text-muted">
        {children}
      </blockquote>
    ),
  };

/* ─── Component ──────────────────────────────────── */

export function MessageContent({ text, isStreaming }: MessageContentProps) {
  const { sealed, pending } = useMemo(() => splitRevealUnits(text), [text]);

  // During streaming, only show sealed (complete) units.
  // When streaming ends, append the final pending unit too.
  const visibleUnits = isStreaming
    ? sealed
    : pending
      ? [...sealed, pending]
      : sealed;

  if (visibleUnits.length === 0) return null;

  return (
    <div className="space-y-2">
      {visibleUnits.map((unit, i) => {
        if (unit.type === 'openui') {
          return (
            <GeneratedCard key={i}>
              <Renderer response={unit.content} library={bestpathLibrary} />
            </GeneratedCard>
          );
        }

        return (
          <div
            key={i}
            className="animate-fade-in-up text-body-sm leading-relaxed text-text-primary"
          >
            <ReactMarkdown components={mdComponents}>
              {unit.content}
            </ReactMarkdown>
          </div>
        );
      })}
    </div>
  );
}
